general.import = [
"~/.config/alacritty/themes/catppuccin-mocha.toml"
]
[window]
 decorations = "None"       
 startup_mode = "Maximized"  

[scrolling]
 history = 5000

[font]
size = 14

[font.bold]
family = "Lilex Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Lilex Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Lilex Nerd Font"
style = "Italic"


[font.normal]
family = "Lilex Nerd Font"
style = "Regular"
