#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pkill picom
picom -b &
nitrogen --restore &
$HOME/.config/polybar/launch.sh 

bspc monitor -d I II III IV 

### GAPS ###
bspc config window_gap          12
bspc config border_width         1

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

# Rosé pine 
bspc config focused_border_color "#9ccfd8"
bspc config normal_border_color "#6e6a86"

